config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
	get 'about' => 'home#about'
  get 'end_users/end_users/edit' => 'end_users#edit'

	devise_for :end_users, skip: :all

  devise_scope :end_user do
    get 'end_users/sign_up', to: 'end_users/registrations#new', as: :new_end_user_registration
    post 'end_users/sign_up', to: 'end_users/registrations#create', as: :end_user_registration
    post 'end_users/registration', to: 'end_users/registrations#edit'
    patch 'end_users/registration', to: 'end_users/registrations#update'
    put 'end_users/registration', to: 'end_users/registrations#update'
    delete 'end_users/registration', to: 'end_users/registrations#destroy'
    get 'end_users/sign_in', to: 'end_users/sessions#new', as: :new_end_user_session
    post 'end_users/sign_in', to: 'end_users/sessions#create', as: :end_user_session
    delete 'end_users/sign_out', to: 'end_users/sessions#destroy', as: :destroy_end_user_session
    get 'end_users/password/new', to: 'end_users/passwords#new', as: :new_end_user_password
    post 'end_users/password', to: 'end_users/passwords#create'
    get 'end_users/password/edit', to: 'end_users/passwords#edit', as: :edit_end_user_password
    patch 'end_users/password', to: 'end_users/passwords#update'
    put 'end_users/password', to: 'end_users/passwords#update'

  end

  resources :genres, only: [:show]
	resources :items, only: [:index, :show]

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :destroy, :update]
  resources :genres, only: [:show]
	resources :deliveries, except: [:new, :show]
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
	resources :orders, only: [:index, :show, :new, :create]

	post 'orders/confirm' => 'orders#confirm'
	get 'orders/thanks' => 'orders#thanks'
	resource :end_users, only: [:show, :update]
  get 'end_users/end_users/password_edit' => 'end_users#password_edit'
  put 'end_users/end_users/password_edit' => 'end_users#password_update'

	get 'end_users/withdraw' => 'end_users#withdraw'
	patch 'end_users/out' => 'end_users#out'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    root 'home#top'
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update]
    get 'end_user_index/:id' => 'orders#end_user_index'
    resources :order_details, only: [:update]
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :end_user
  belongs_to :item

  validates :number, presence: true

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  before_action :authenticate_end_user!

  def index
    @end_user = current_end_user
    @cart_items = @end_user.cart_items.all
  end

  def create
    @end_user = current_end_user
    @cart_item = current_end_user.cart_items.new(cart_item_params)
    @current_item = CartItem.find_by(item_id: @cart_item.item_id, end_user_id: @cart_item.end_user.id)
    if @current_item.nil?
      if @cart_item.save
        flash[:notice] = "カートに商品が追加されました"
        redirect_to cart_items_path
      else
        @carts_items = @end_user.cart_items.all
        render 'index'
      end
    else
      amount = @current_item.number + params[:cart_item][:number].to_i
      @current_item.update(number: amount)
      redirect_to cart_items_path
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
    flash[:notice] = "カート内の商品を取り消しました"
  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      flash[:notice] = "カート内の商品を更新しました"
      redirect_to cart_items_path
    end
  end

  def destroy_all
    @end_user = current_end_user
    @end_user.cart_items.destroy_all
    redirect_to cart_items_path
    flash[:notice] = "カートを空にしました"
  end


  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :end_user_id, :number)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-10">
      <h4><mark>ショッピングカート</mark></h4>
    </div>
    <div class="col-md-11">
    <!-- カートを空にする -->
      <p class="text-right">
        <%= link_to "カートを空にする", cart_items_destroy_all_path, method: :delete, class: "btn btn-danger" %>
      </p>
    </div>
  </div>
</div>
<!-- カート内訳 -->
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table cart_table">
      <thead class="cart_thead">
        <tr>
          <th colspan="2" class="text-center">商品名</th>
          <th class="text-center">単価（税込）</th>
          <th class="text-center">数量</th>
          <th class="text-center">小計</th>
          <th></th>
        </tr>
      </thead>
      <tbody class="cart_tbody">
        <% @cart_items.each do |cart_item| %>
        <tr style="font-size: 15px;">
          <td colspan="2",width="120px"><%= attachment_image_tag cart_item.item, :image, :fill, 80, 80 %>  <%= cart_item.item.name %></td>
          <td class="text-right"><%= price_tax(cart_item.item.price_nontax).to_s(:delimited) %></td>
          <td class="text-right">
            <%= form_with model: cart_item, local: true do |f| %>
              <%= f.number_field :number, value: cart_item.number, min: 1, max: 10 %>
              <%= f.submit "変更", class: "btn btn-primary" %>
            <% end %>
          </td>
          <td class="text-right">  <!-- 小計計算 -->
            <%= sub_price(cart_item).to_s(:delimited) %>
          </td>
          <td class="text-center">
            <%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn btn-danger" %>
          </td>
        </tr>
        <% end %>
        <tr style="font-size: 15px;">
          <td colspan="4">
          <td class="cart_total text-center"><strong>合計金額</strong></td>
          <td class="text-right">  <!-- 合計金額計算 -->
            <%= total_price(@cart_items).to_s(:delimited) %>
          </td>
        </tr>
    </tbody>
    </table>
  </div>
</div>
<!-- 情報入力ボタン -->
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <p><%= link_to "買い物を続ける", root_path, class: "btn btn-primary btn-block btn-lg" %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <p><%= link_to "情報入力に進む", new_order_path, class: "btn btn-success btn-block btn-lg" %></p>
  </div>
</div>