config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
	get 'about' => 'home#about'
  get 'end_users/end_users/edit' => 'end_users#edit'

	devise_for :end_users, skip: :all

  devise_scope :end_user do
    get 'end_users/sign_up', to: 'end_users/registrations#new', as: :new_end_user_registration
    post 'end_users/sign_up', to: 'end_users/registrations#create', as: :end_user_registration
    post 'end_users/registration', to: 'end_users/registrations#edit'
    patch 'end_users/registration', to: 'end_users/registrations#update'
    put 'end_users/registration', to: 'end_users/registrations#update'
    delete 'end_users/registration', to: 'end_users/registrations#destroy'
    get 'end_users/sign_in', to: 'end_users/sessions#new', as: :new_end_user_session
    post 'end_users/sign_in', to: 'end_users/sessions#create', as: :end_user_session
    delete 'end_users/sign_out', to: 'end_users/sessions#destroy', as: :destroy_end_user_session
    get 'end_users/password/new', to: 'end_users/passwords#new', as: :new_end_user_password
    post 'end_users/password', to: 'end_users/passwords#create'
    get 'end_users/password/edit', to: 'end_users/passwords#edit', as: :edit_end_user_password
    patch 'end_users/password', to: 'end_users/passwords#update'
    put 'end_users/password', to: 'end_users/passwords#update'

  end

  resources :genres, only: [:show]
	resources :items, only: [:index, :show]

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :destroy, :update]
  resources :genres, only: [:show]
	resources :deliveries, except: [:new, :show]
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
	resources :orders, only: [:index, :show, :new, :create]

	post 'orders/confirm' => 'orders#confirm'
	get 'orders/thanks' => 'orders#thanks'
	resource :end_users, only: [:show, :update]
  get 'end_users/end_users/password_edit' => 'end_users#password_edit'
  put 'end_users/end_users/password_edit' => 'end_users#password_update'

	get 'end_users/withdraw' => 'end_users#withdraw'
	patch 'end_users/out' => 'end_users#out'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    root 'home#top'
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update]
    get 'end_user_index/:id' => 'orders#end_user_index'
    resources :order_details, only: [:update]
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  validates :name, presence: true
  validates :explanation, presence: true
  validates :price_nontax, presence: true
  validates :image, presence: true

	attachment :image
  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
  	@items = Item.all.page(params[:page]).per(2)
  end

  def show
  	@item = Item.find(params[:id])
    @price_tax = @item.price_nontax.to_i*1.1
  end

  def new
  	@item = Item.new
  	@genres = Genre.all
  end

  def create
    @genres = Genre.all
  	@item = Item.new(item_params)
  	if @item.save
      flash[:notice] = "新たに商品が追加されました"
  	  redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def edit
  	@item = Item.find(params[:id])
  	@genres = Genre.all
  end

  def update
  	@item = Item.find(params[:id])
  	@genres = Genre.all
  	if @item.update(item_params)
      flash[:notice] = "商品情報を更新しました"
  		redirect_to admins_items_path
  	else
  		render :edit
  	end
  end

 private

 def item_params
 	params.require(:item).permit(:genre_id, :name, :explanation, :price_nontax, :image, :sale_status)
 end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
  	@items = Item.page(params[:page]).reverse_order
  	@genres = Genre.all
  end

  def show
  	@item = Item.find(params[:id])
    @cart_item = @item.cart_items.build
    @genres = Genre.all
  end

end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_genre_sidebar.html.erb
<div class="col-md-2">
  <nav class="genre-area">
    <div class="genre-title"><%= image_tag('icon2.png') %> ジャンル検索</div>
    <ul>
      <% genres.each do |genre| %>
        <li>
          <%= link_to genre.name, genre_path(genre) %>
        </li>
      <% end %>
    </ul>
  </nav>
  <div>
    <%= image_tag('usagi4.png', size: "240x270") %>
  </div>
</div>

app/views/items/edit.html.erb
<div class="container">
	<h2>商品編集</h2>
	<div class="row">
		<%= form_for(@item, url: admins_item_path) do |f| %>
			<div class="col-md-4">
				<div class="row">
					<%= f.attachment_field :image, class: "col-md-12" %>
				</div>
			</div>
			<div class="col-md-8">
				<div>
					<%= f.label :name, "商品名" %>
					<%= f.text_field :name %>
				</div>
				<div>
					<%= f.label :explanation, "商品説明" %>
					<%= f.text_area :explanation %>
				</div>
				<div>
					<%= f.label :genre, "ジャンル" %>
					<%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --") %>
				</div>
				<div>
					<%= f.label :price_nontax, "税抜価格" %>
					<%= f.text_field :price_nontax  %><span>円</span>
				</div>
				<div>
					<%= f.label :sale_status, "販売ステータス" %>
					<%= f.select :sale_status, [['販売中', true], ['売り切れ', false]], prompt: "-- 選択してください --" %>
				</div>
			</div>
			<div class="row">
				<%= f.submit "変更を保存", class: "btn btn-primary col-md-offset-7" %>
			</div>
		<% end %>
	</div>
</div>

app/views/items/index.html.erb
<div class="row">
	<!-- ジャンル検索サイドバー -->
  <%= render 'items/genre_sidebar', genres: @genres %>

		<div class="col-md-9 col-md-offset-1">
			<h1>商品一覧 <span style="font-size: 20px;">(全<%= @items.count %>件)</span></h1>
			<div class="row">
				<% @items.each do |item| %>
					<div class="col-md-3">
						<% if item.genre.is_valid == true && item.sale_status == true %>
							<%= link_to item_path(item) do %>
								<%= attachment_image_tag item, :image, format: 'jpeg', size:"200x150" %>
								<p><%= item.name %></p>
							<% end %>
							<p>￥<%= item.price_nontax.to_s(:delimited) %>(税抜)</p>
						<% elsif item.sale_status == false %>
							<%= attachment_image_tag item, :image, format: 'jpeg', size:"200x150" %>
							<p><%= item.name %></p>
							<p style="background-color: red; color: white; width: 30%;">売り切れ</p>
						<% elsif item.genre.is_valid == false %>
										<%= image_tag 'あつかいない.png', :size => '200x150' %>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="text-center">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<div class="row">
	<!-- ジャンル検索サイドバー -->
  <%= render 'items/genre_sidebar', genres: @genres %>

	<div class="col-md-4 col-md-offset-1">
		<%= attachment_image_tag @item, :image, :fill, 350, 250, format: 'jpeg', fallback: "no_image.png" %>
	</div>
	<div class="col-md-5">
		<div class="row">
		  <h2><%= @item.name %></h2>
		  <h4><%= @item.explanation %></h4>
		  <h3>¥<%= price_tax(@item.price_nontax).to_s(:delimited) %>(税込)</h3>
		</div>
		<div class="row">
			<div class="col-md-12">
				<%= form_for(@cart_item, url: cart_items_path) do |f| %>
				  <div class="col-md-4 col-md-offset-4">
					  <%= f.number_field :number, placeholder: "個数選択", min: 1, max: 10, class: "form-control" %>
					  <%= f.hidden_field :item_id, value: @item.id %>
					</div>
					<div class="col-md-4">
					  <%= f.submit "カートに入れる", class: "btn btn-primary" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>