config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
	get 'about' => 'home#about'
  get 'end_users/end_users/edit' => 'end_users#edit'

	devise_for :end_users, skip: :all

  devise_scope :end_user do
    get 'end_users/sign_up', to: 'end_users/registrations#new', as: :new_end_user_registration
    post 'end_users/sign_up', to: 'end_users/registrations#create', as: :end_user_registration
    post 'end_users/registration', to: 'end_users/registrations#edit'
    patch 'end_users/registration', to: 'end_users/registrations#update'
    put 'end_users/registration', to: 'end_users/registrations#update'
    delete 'end_users/registration', to: 'end_users/registrations#destroy'
    get 'end_users/sign_in', to: 'end_users/sessions#new', as: :new_end_user_session
    post 'end_users/sign_in', to: 'end_users/sessions#create', as: :end_user_session
    delete 'end_users/sign_out', to: 'end_users/sessions#destroy', as: :destroy_end_user_session
    get 'end_users/password/new', to: 'end_users/passwords#new', as: :new_end_user_password
    post 'end_users/password', to: 'end_users/passwords#create'
    get 'end_users/password/edit', to: 'end_users/passwords#edit', as: :edit_end_user_password
    patch 'end_users/password', to: 'end_users/passwords#update'
    put 'end_users/password', to: 'end_users/passwords#update'

  end

  resources :genres, only: [:show]
	resources :items, only: [:index, :show]

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :destroy, :update]
  resources :genres, only: [:show]
	resources :deliveries, except: [:new, :show]
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
	resources :orders, only: [:index, :show, :new, :create]

	post 'orders/confirm' => 'orders#confirm'
	get 'orders/thanks' => 'orders#thanks'
	resource :end_users, only: [:show, :update]
  get 'end_users/end_users/password_edit' => 'end_users#password_edit'
  put 'end_users/end_users/password_edit' => 'end_users#password_update'

	get 'end_users/withdraw' => 'end_users#withdraw'
	patch 'end_users/out' => 'end_users#out'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    root 'home#top'
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update]
    get 'end_user_index/:id' => 'orders#end_user_index'
    resources :order_details, only: [:update]
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone, presence: true


  enum is_deleted: { 有効: false, 退会済み: true }
def active_for_authentication?
        super && (self.is_deleted === "有効")
    end

end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users = EndUser.page(params[:page]).per(2)
  end

  def show
    @user = EndUser.find(params[:id])
  end

  def edit
    @user = EndUser.find(params[:id])
  end

  def update
    @user = EndUser.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を更新しました"
      redirect_to admins_end_users_path
    else
      render :edit
    end
  end

 private

 def user_params
  params.require(:end_user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone, :email, :is_deleted)
 end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected
  # 追記する
  def after_update_path_for(resource)
    end_users_end_users_edit_path
  end
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController

  before_action :authenticate_end_user!

  def show
    @user = current_end_user
  end

  def edit
  	@user = current_end_user
  end

  def update
    @user = current_end_user
    if @user.update(end_user_params)
      flash[:notice] = "会員情報を更新しました"
      redirect_to end_users_path
    else
      render :edit
    end
  end

  def withdraw
    @user = current_end_user
  end

  def index
  end

  def out
    @user = current_end_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def password_edit
    @user = current_end_user
  end
  
  def password_update
    @user = current_end_user
    @user.update(end_user_params)
    redirect_to end_users_path
  end

  private
  def end_user_params
    params.require(:end_user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :email,  :phone, :is_deleted, :password)
  end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/edit.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<h4><mark>登録情報編集</mark></h4>
	</div>
</div>
<%= form_for(@user, url: end_users_path, method: :patch) do |f| %>
<!-- エラーメッセージ -->
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group row">
			<label class="col-md-3 control-label">名前</label>
			<label class="col-md-1 control-label">(姓)</label>
			<div class="col-md-3">
				<%= f.text_field :first_name,autofocus:true,autocomplete: "first_name", class: "form-control" %>
			</div>
			<label class="col-md-1 control-label">(名)</label>
			<div class="col-md-3">
				<%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group row">
			<label class="col-md-3 control-label">フリガナ</label>
			<label class="col-md-1 control-label">(セイ)</label>
			<div class="col-md-3">
				<%= f.text_field :first_name_kana, autofocus:true, autocomplete: "first_name_kana", class: "form-control" %>
			</div>
			<label class="col-md-1 control-label">(メイ)</label>
			<div class="col-md-3">
				<%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: "form-control" %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group row">
			<label class="col-md-4 control-label">メールアドレス</label>
			<div class="col-md-7">
				<%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control"%>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group row">
			<label class="col-md-4 control-label">郵便番号(ハイフンなし)</label>
			<div class="col-md-7">
				<%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "form-control" %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group row">
			<label class="col-md-4 control-label">住所</label>
			<div class="col-md-7">
				<%= f.text_field :address, autofocus: true,autocomplete: "address", class: "form-control" %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group row">
			<label class="col-md-4 control-label">電話番号(ハイフンなし)</label>
			<div class="col-md-3">
				<%= f.telephone_field :phone, autofocus: true, autocomplete: "phone", class: "form-control" %>
			</div>
		</div>
	</div>
</div>
	<div class="row">
		<div class="col-md-2 col-md-offset-4">
			<%= f.submit "編集内容を保存する", class: "btn btn-primary btn-block" %>
		</div>
		<div class="col-md-2 col-md-offset-1">
			<%= link_to "退会する", end_users_withdraw_path, class: "btn btn-danger btn-block" %>
			<% end %>
		</div>
	</div>

app/views/end_users/index.html.erb
<h1>EndUsers#index</h1>
<p>Find me in app/views/end_users/index.html.erb</p>

app/views/end_users/password_edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2>パスワード再設定</h2>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<%= form_for(@user, url: end_users_end_users_password_edit_path, html: { method: :put }) do |f| %>
  	<%= f.hidden_field :reset_password_token %>
	</div>
</div>
<div class="field">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
    	<%= f.label :password, "新しいパスワード" %><br/>
    	<% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em><br/>
    	<% end %>
  	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
    <%= f.password_field :password, autofocus: true, autocomplete: "new-password" %>
  </div>
</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
  <div class="field">
    <%= f.label :password_confirmation, "新しいパスワード(確認用)" %><br/>
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>
</div>
</div>
<div class="row">
	<div class="col-md-2 col-md-offset-2">
  <div class="actions">
    <%= f.submit "パスワードを変更する", class: "btn btn-primary btn-block" %>
  </div>
</div>
</div>
  </div>
<% end %>
</div>

app/views/end_users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-10">
      <h4><mark>マイページ</mark></h4>
    </div>
  </div>
</div>
<div class="row">
	<div class="col-md-2">
		<p><b>登録情報<b></p>
	</div>
	<div class="col-md-4">
		<%= link_to "編集する", end_users_end_users_edit_path, class: "btn btn-primary" %>
		<%= link_to "パスワードを変更する", end_users_end_users_password_edit_path, class: "btn btn-primary" %>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<table class="table table-bordered">
			<tr>
				<td>氏名</td>
				<td><%= "#{@user.first_name} #{@user.last_name}" %></td>
			</tr>
			<tr>
				<td>カナ</td>
				<td><%= "#{@user.first_name_kana} #{@user.last_name_kana}" %></td>
			</tr>
			<tr>
				<td>郵便番号</td>
				<td><%= @user.postal_code %></td>
			</tr>
			<tr>
				<td>住所</td>
				<td><%= @user.address %></td>
			</tr>
			<tr>
				<td>電話番号</td>
				<td><%= @user.phone %></td>
			</tr>
			<tr>
				<td>メールアドレス</td>
				<td><%= @user.email %></td>
			</tr>
		</table>
	</div>
</div>
<div class="row">
	<div class="col-md-2">
		<p>配送先</p>
	</div>
	<div class="col-md-4">
		<%= link_to "一覧を見る", deliveries_path, class: "btn btn-primary" %>
	</div>
</div>
<div class="row">
	<div class="col-md-2">
		<p>注文履歴</p>
	</div>
	<div class="col-md-4">
		<%= link_to "一覧を見る", orders_path(order_sort: 1), class: "btn btn-primary" %>
	</div>
</div>

app/views/end_users/withdraw.html.erb
<div class="roew">
	<div class="col-md-8 col-md-offset-4">
		<h2><b>本当に退会しますか？</b></h2>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-4">
		<P>退会すると、会員情報や</P><br>
		<p>これまでの購入履歴が閲覧できなくなります。</p><br>
		<p>退会する場合は、「退会する」をクリックしてください。</p>
	</div>
</div>
<div class="row">
	<div class="col-md-3 col-md-offset-4">
		<%= link_to "退会しない", end_users_path, class: "btn btn-primary" %>
	</div>
	<div class="col-md-3">
		<%= link_to "退会する", end_users_out_path, method: :patch, class: "btn btn-danger" %>
	</div>
</div>
</div>